### ISSUE TITLE
preg_split() causing deprecation warnings in PHP 8.1

### ISSUE THREAD

**Issue by sig-mmiddleton** [signify-nz/silverstripe-mailblock#3]
Running Mailblock on a SilverStripe 4.11 site with PHP 8.1, receiving following error warning:

> [Deprecated] preg_split(): Passing null to parameter # 2 ($subject) of type string is deprecated.

From a quick look, it seems this could be resolved by edits to code/email/MailblockPlugin.php

```
- $whitelist = preg_split("/\r\n|\n|\r/", $mailblockWhitelist);
+ $whitelist = !empty($mailblockWhitelist) ? preg_split("/\r\n|\n|\r/", $mailblockWhitelist) : [];

- $newRecipients = preg_split("/\r\n|\n|\r/", $mailblockRecipients);
+ $newRecipients = !empty($mailblockRecipients) ? preg_split("/\r\n|\n|\r/", $mailblockRecipients) : [];
```

**Comment by sig-mmiddleton** [comment]
Raised as SIGMAS-239

**Comment by LeviWB** [comment]
Thanks @sig-mmiddleton. Closing this now after your contribution https://github.com/signify-nz/silverstripe-mailblock/commit/20db9d9bb9b4438abe331fea88d1560709a921bb
